### ISSUE TITLE
petit probléme d'icone

### ISSUE THREAD

**Issue by etopit** [snipsco/Snips-JeeDom-Plugin#12]
rien de bien méchant le fichier snips.php dans plugins/snips/desktop/php/ référence les images dans /plugins/snips/3rdparty/icons/ 

sur mon installation de jeedom la racine du site web jeedom n'est pas à la racine "/" mais /jeedom/

**Comment by CoorFun** [comment]
Bonjour,

Je pense que nous aurons Jeedom V4 dans les prochains mois. Cela peut résoudre ton problème. Pour le moment, il n’est pas si facile d’adapter votre situation car jeedom aura besoin d’un répertoire absolu pour récupérer des icônes.
