### ISSUE TITLE
scenario variable `snipsMsgHotwordId` isn't set

### ISSUE THREAD

**Issue by CoorFun** [snipsco/Snips-JeeDom-Plugin#18]
@KiboOst

**Comment by CoorFun** [comment]
@KiboOst  I confirm that it's a bug. Now it's been corrected.

**Comment by KiboOst** [comment]
Sorry but can't confirm that.

- installed last stable. Like previous one, had to manually restart the demon. 
- unchecked and checked snipsMsgHotwordId  option, restarted the demon, and did a test. Still no variable set. No log, just nothing.

**Comment by CoorFun** [comment]
Sorry, I forget to push to jeedom....

**Comment by CoorFun** [comment]
Should be okay now.

**Comment by KiboOst** [comment]
Ok, this time has the option unchecked after the update which is in line with your update script!

Checked, restarted daemon, and.... it works !!!

Everything good now on my side ;-)
Many thanks dude !
