### ISSUE TITLE
Ideas : get start session intent in jeedom

### ISSUE THREAD

**Issue by fwehrle** [snipsco/Snips-JeeDom-Plugin#2]
Hi,

It would be usefull to get the snips client's "start session" mqtt intent in jeedom. To make actions, like turn on lamps, turn volume down, etc...

**Comment by fwehrle** [comment]
Idem when a intent has no binding

**Comment by CoorFun** [comment]
Not sure I understand this idea. When an intent has been detected, this will be captured by the plugin anyway no?

**Comment by fwehrle** [comment]
Yes, the intent is captured by the plugin, but there is no way to launch a scenario if no binding are detected. So the plugin say the default sentence. It would be cool to have the possibility to launch a scenario for an intent with no binding detected. 
And for my first idea : BEFORE the binding is detected, it would be usefull to detect when someone say the hotword "Hey snips" => launch a scenario.

**Comment by CoorFun** [comment]
In fact, the intent detection is the only trigger of any actions. `hotword detected` signal or `session start` signal can also mean an `intent not recognized` . For your idea, maybe we can set a variable/ command which will be updated when an intent detected, then this updating can be the trigger of the scenario?

**Comment by fwehrle** [comment]
Yes, as a scenario can be triggered by a variable. So it do the job.
But can you set a variable or command on session start if no intent where detected?

**Comment by CoorFun** [comment]
I think it's possible for sure, but to change this we need a "good" reason. I am wondering that if there is no intent detected, how can you use this session start signal?

**Comment by fwehrle** [comment]
My reason is simple : 
I would like to down the TV/music volume when a session start/a hotword is detected.

And I would like to know / run a scenario when no bindings are detected for the incoming intent.

**Comment by CoorFun** [comment]
It's a good idea though. So it means that you may have a better "sound environment" to speak your query? If so I would say the end session should also be an event to trigger the reverse scenario? 
Will take into consideration.

**Comment by fwehrle** [comment]
That's it!
The best is to have all this trigger : 
- start session
- end session 
- no binding found for an intent.

Thank you :)

**Comment by CoorFun** [comment]
Please check out the latest [Beta] branch (Also released beta on Jeedom market). 

It added a variable (snipsMsgSession), this variable will be assigned the session id when a session started. Then when the session ended, this variable will be assigned with an empty string.

This can be the trigger of a scenario : )

**Comment by fwehrle** [comment]
I'll check and test it as soon as it will be available.
Thank you very much.

When we start a scenario with snipsMsgSession, is it possible to check the SiteId ?

**Comment by fwehrle** [comment]
Hi @CoorFun : I didn't see any update from Snips Plugin on my jeedom.
I'm set up with the git repository.
Is it normal?

**Comment by CoorFun** [comment]
Probably you have the stable version installed? I will merge this to stable these 2 days since today I would push a little configuration change to beta branch. All of these will be merged to master within this week.

**Comment by fwehrle** [comment]
Hum... I don't think..
Is there a way to going back to the beta without loozing equipments and settings?
