### ISSUE TITLE
/etc/apt/sources.list.d/mosquitto-stretch.list.N

### ISSUE THREAD

**Issue by Jeandhom** [snipsco/Snips-JeeDom-Plugin#20]
The script that installs the packages needed by the plugin tries to create an already existing file and we end up with:

/etc/apt/sources.list.d/mosquitto-stretch.list.1
/etc/apt/sources.list.d/mosquitto-stretch.list.2
/etc/apt/sources.list.d/mosquitto-stretch.list.3
…
/etc/apt/sources.list.d/mosquitto-stretch.list.N

Plugin's log:
--2019-03-22 21:57:57--  http://repo.mosquitto.org/debian/mosquitto-stretch.list
Resolving repo.mosquitto.org (repo.mosquitto.org)... 85.119.83.194, 2001:ba8:1f1:f271::2
Connecting to repo.mosquitto.org (repo.mosquitto.org)|85.119.83.194|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51 [application/octet-stream]
Saving to: 'mosquitto-stretch.list.2'

Stretch upgrade log:
N: « mosquitto-stretch.list.1 » dans le répertoire « /etc/apt/sources.list.d/ » a été ignoré car il utilise une extension non valable
N: « mosquitto-stretch.list.2 » dans le répertoire « /etc/apt/sources.list.d/ » a été ignoré car il utilise une extension non valable

**Comment by Jeandhom** [comment]
En attendant la correction du bug :

rm -i /etc/apt/sources.list.d/mosquitto-stretch.list.*

**Comment by CoorFun** [comment]
hello,

This issue is solved in the latest release - `0.1.4`.

Thanks for reporting!

**Comment by Jeandhom** [comment]
Thanks for your work.
