### ISSUE TITLE
Jeedom smart 3.3.20, plugin 0.1.4 Installation dépendances impossible, plantage Jeedom.

### ISSUE THREAD

**Issue by Fil17** [snipsco/Snips-JeeDom-Plugin#22]
Bonjour à tous.
Je suis nouveau sur ce forum. En 3 jours je n'ai pas réussi à installer snips sur Jeedom. Pire, dès que le plugin est activé, les fonctionnalités de Jeedom se dégradent (ralentissement), et même un plantage avec necessité de relancer Jeedom en coupant l'alimentation.
Snips est installé sur un Maker kits, qui fonctionne bien par ailleur.
Le log de l'installation des dépendances est joint ici : 
[snips_dep.txt](https://github.com/snipsco/snips-jeedom-plugin/files/3083600/snips_dep.txt)
J'ai besoin d'aide, et je suis très déçu de ce résultat !

**Comment by CoorFun** [comment]
Hello,

It seems the problem comes from the OS Debian Jessie where your Jeedom is running. 

I have found an answer here: 
https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository

Try to modify the source list url and re-launch the dependency installation.

**Comment by Fil17** [comment]
Thank you, i see that.
