### ISSUE TITLE
Dependencies are still NOK 

### ISSUE THREAD

**Issue by qalidor** [snipsco/Snips-JeeDom-Plugin#24]
Hello,
I have a strange bug with the plugin:
The dependencies are still NOK but according to the logs all the dependencies are already installed but the demon does not want to start.
When I wanted to load the assistant via the Plugin, I entered the user and the password I had an error message asking me to check my configuration but the assistant appeared still loaded but it is not functional ....
But the demon does not want to start anymore.
I try to install the plugin manually from git but same problem.
I am on Debian 9 stretch (up to date)
![Plugin1](https://user-images.githubusercontent.com/534886/60832588-87749980-a1bc-11e9-81fb-7d01af804ced.png)
![Plugin2](https://user-images.githubusercontent.com/534886/60832593-89d6f380-a1bc-11e9-8b94-f3404f8613c5.png)
![Plugin3](https://user-images.githubusercontent.com/534886/60832597-8c394d80-a1bc-11e9-94f3-c56c4a433da7.png)
![Plugin4](https://user-images.githubusercontent.com/534886/60832602-8d6a7a80-a1bc-11e9-83a7-a8565edfc2da.png)

**Comment by qalidor** [comment]
Hi,
I find the problem of dependencies that always appear in "NOK" with the daemon that does not start.
In the installation script of the plugin, he tries to install the version "Mosquitto-alpha" (command of the script: "pecl install Mosquitto-alpha") except apparently this version is not available on the repo, I have fixed the problem by manually installing the beta version of the Mosquitto extension by typing the command: sudo pecl install Mosquitto-beta.

**Comment by CoorFun** [comment]
Hello @qalidor , 

Thank you very much. I will make the change as soon as possible
