### ISSUE TITLE
bug in snips.binding.scenario.class.php

### ISSUE THREAD

**Issue by oguh22** [snipsco/Snips-JeeDom-Plugin#27]
Hello,

An old reported issue appears again in the last version of the plugin
in the file snips.binding.scenario.class.php at line 48 :
        $args = arg2array($**thsi**->user_tags);
instead of **$this**

Regards,
Hugo

**Comment by CoorFun** [comment]
Thanks Hugo, it's fixed https://github.com/snipsco/snips-jeedom-plugin/tree/b82efd83176952801a1f640ab00690dd1dfd8706
