### ISSUE TITLE
snips::deamon_hermes() : Call to a member function getName() on boolean

### ISSUE THREAD

**Issue by oguh22** [snipsco/Snips-JeeDom-Plugin#28]
Not able to use snips binding action on new plugin version ...
snips::deamon_hermes() : Call to a member function getName() on boolean

**Comment by CoorFun** [comment]
It's not been updated since 6 months ago. Which version you are on?

**Comment by oguh22** [comment]
@CoorFun , I am on version 2019-04-10 15:28:35 and Jeedom propose to update to 2019-10-03 11:59:44
I have to revert back my jeedom to an old backup to stay on the working version.

**Comment by CoorFun** [comment]
Really fixed. [Reference](https://github.com/snipsco/snips-jeedom-plugin/commit/fdb09dbc032b669e687a380403072260821f9734)
