### ISSUE TITLE
Erreur sur snips::deamon_hermes() : Call to a member function getName() on boolean

### ISSUE THREAD

**Issue by marcteyssier** [snipsco/Snips-JeeDom-Plugin#29]
Hi

I have this error on my Jeedom plugin on intent OpenCoverJeedom, it work for CloseCoverJeedom.
I have snips in version 0.64, I have reload my assistant.
Jeedom snips plugin : 2019-10-03 11:59:44

I don't know how the issue is fixed #28  

> [2019-10-08 16:10:58][DEBUG] : [SnipsHermes] <mqtt_on_subscribe> subscribeed with code 1
> [2019-10-08 16:10:58][DEBUG] : [SnipsHermes] <mqtt_on_subscribe> subscribeed with code 2
> [2019-10-08 16:10:58][DEBUG] : [SnipsHermes] <mqtt_on_subscribe> subscribeed with code 3
> [2019-10-08 16:10:58][DEBUG] : [SnipsHermes] <mqtt_on_subscribe> subscribeed with code 4
> [2019-10-08 16:11:03][DEBUG] : [SnipsHermes] <mqtt_on_message> received message. topic:hermes/hotword/default/detected
> [2019-10-08 16:11:03][DEBUG] : [SnipsHandler] <hotword_detected>
> [2019-10-08 16:11:03][DEBUG] : [SnipsHermes] <mqtt_on_message> received message. topic:hermes/dialogueManager/sessionStarted
> [2019-10-08 16:11:03][DEBUG] : [SnipsHandler] <check_site_id_existnce>
> [2019-10-08 16:11:03][DEBUG] : [SnipsUtils] <get_snips_intent_object> Jeedom >= 3.3.3
> [2019-10-08 16:11:03][DEBUG] : [SnipsUtils] <get_snips_intent_object> Jeedom >= 3.3.3
> [2019-10-08 16:11:03][DEBUG] : [SnipsHandler] <session_started>
> [2019-10-08 16:11:08][DEBUG] : [SnipsHermes] <mqtt_on_message> received message. topic:hermes/intent/Kram:OpenCoverJeedom
> [2019-10-08 16:11:08][DEBUG] : [SnipsHermes] <mqtt_publish> published message: {"sessionId":"2bc77283-7526-480a-a1df-ee65ce122f72"} to topic: hermes/dialogueManager/endSession
> [2019-10-08 16:11:08][INFO] : [SnipsHandler] <intent_detected> jeedom intent detected :Kram:OpenCoverJeedom
> [2019-10-08 16:11:08][DEBUG] : [SnipsUtils] <extract_slots_value>
> [2019-10-08 16:11:08][DEBUG] : [SnipsUtils] <set_slot_cmd>
> [2019-10-08 16:11:08][DEBUG] : [SnipsUtils] <set_slot_cmd> slots name is :house_room
> [2019-10-08 16:11:08][ERROR] : Erreur sur snips::deamon_hermes() : Call to a member function getName() on boolean
> [2019-10-08 16:11:08][DEBUG] : [SnipsHermes] <mqtt_on_disconnect> disconnected from the broker with code: 0

Thank you
Marc

**Comment by JoumForge** [comment]
Bonjour,

Je rencontre le même dysfonctionnement signalé par "Marc" depuis la mise à jour de mon plugin sur Jeedom en 0.1.4. Je viens d'installer la version 0.1.5 mais cela ne règle pas ce problème.

> [2019-10-09 18:00:32][DEBUG] : [SnipsHermes] <mqtt_on_message> received message. topic:hermes/hotword/default/detected
[2019-10-09 18:00:32][DEBUG] : [SnipsHandler] <hotword_detected>
[2019-10-09 18:00:32][DEBUG] : [SnipsHermes] <mqtt_on_message> received message. topic:hermes/dialogueManager/sessionStarted
[2019-10-09 18:00:32][DEBUG] : [SnipsHandler] <check_site_id_existnce>
[2019-10-09 18:00:32][DEBUG] : [SnipsUtils] <get_snips_intent_object> Jeedom >= 3.3.3
[2019-10-09 18:00:32][DEBUG] : [SnipsUtils] <get_snips_intent_object> Jeedom >= 3.3.3
[2019-10-09 18:00:32][DEBUG] : [SnipsHandler] <session_started>
[2019-10-09 18:00:35][DEBUG] : [SnipsHermes] <mqtt_on_message> received message. topic:hermes/intent/valf:TurnOnJeedom
[2019-10-09 18:00:35][DEBUG] : [SnipsHermes] <mqtt_publish> published message: {"sessionId":"60aeba30-3161-4f9d-900a-5a649fd8e704"} to topic: hermes/dialogueManager/endSession
[2019-10-09 18:00:35][INFO] : [SnipsHandler] <intent_detected> jeedom intent detected :valf:TurnOnJeedom
[2019-10-09 18:00:35][DEBUG] : [SnipsUtils] <extract_slots_value>
[2019-10-09 18:00:35][DEBUG] : [SnipsUtils] <set_slot_cmd>
[2019-10-09 18:00:35][DEBUG] : [SnipsUtils] <set_slot_cmd> slots name is :device_name
**[2019-10-09 18:00:35][ERROR] : Erreur sur snips::deamon_hermes() : Call to a member function getName() on boolean**
[2019-10-09 18:00:35][DEBUG] : [SnipsHermes] <mqtt_on_disconnect> disconnected from the broker with code: 0


En vous remerciant par avance.

Cordialement,

Julien.

**Comment by DarkAdibou** [comment]
Bonjour
J'ai la même erreur sur les 2 intents cover
[2019-10-09 18:00:35][ERROR] : Erreur sur snips::deamon_hermes() : Call to a member function getName() on boolean

**Comment by marcteyssier** [comment]
Note: I have install the last version of jeedom plugin snips and I have the same error :-(
version 2019-10-09 04:09:10
number 0.15
How can I help you ?
I can add logs in the code if it can help you.

Marc

**Comment by marcteyssier** [comment]
Bonjour à tous (tout le monde parle en français alors moi aussi :-P)

J'ai trouvé pourquoi ça ne marchait pas chez moi (après avoir mis des logs à la main dans les fichiers php) !
Dans la page de configuration de jeedom des intents, il faut bien vérifier que vous n'avez pas de scénario callback à vide et non à "none" (après une erreur dans la configuration).
Du coup à chaque action sur cet intent, le plugin snips pour jeedom essayé d'exécuter un scenario qui n'existait pas.
![screen](https://user-images.githubusercontent.com/2227717/66594083-a5c1ab00-eb98-11e9-97a0-b1a129f21145.png)

![screen2](https://user-images.githubusercontent.com/2227717/66594237-018c3400-eb99-11e9-9555-6df5a892e1cc.png)


Techniquement :
Dans le fichier snips-jeedom-plugin/core/class/snips.binding.scenario.class.php
Dans le constructeur $scenario['scenario']=''
Et du coup dans le execute() ça plante !

J'espère que ça vous aidera
Marc

**Comment by JoumForge** [comment]
Bonjour Marc,

Merci beaucoup pour votre partage et la solution qui a résolu notre problème.

Bonne journée,

Julien.

**Comment by CoorFun** [comment]
Thanks Marc,

I did a [fix](https://github.com/snipsco/snips-jeedom-plugin/commit/fdb09dbc032b669e687a380403072260821f9734) for preventing this error happen, it's now alive on `Stable` and `Beta` branch.
